import difflib
import sys
import os

# --- ANSI Escape Codes for Terminal Colors ---
# These codes are used to colorize the output in the terminal.
# They are generally supported by most modern terminals (Linux, macOS, Windows Terminal).
COLOR_RED = "\033[91m"     # For removed lines
COLOR_GREEN = "\033[92m"   # For added lines
COLOR_YELLOW = "\033[93m"  # For '?' lines (indicating character-level differences)
COLOR_RESET = "\033[0m"    # Resets the color back to default

# Map diff prefixes to their respective colors
COLOR_MAP = {
    '-': COLOR_RED,
    '+': COLOR_GREEN,
    '?': COLOR_YELLOW,
    ' ': COLOR_RESET,  # Common lines are displayed in default color
}

def _get_file_content(filepath: str) -> list[str]:
    """
    Reads the content of a file and returns it as a list of strings,
    where each string represents a line in the file.

    Args:
        filepath (str): The path to the file.

    Returns:
        list[str]: A list of lines from the file, stripped of trailing newlines.

    Raises:
        FileNotFoundError: If the specified file does not exist.
        IOError: For other issues during file reading.
    """
    if not os.path.exists(filepath):
        raise FileNotFoundError(f"Error: File not found at '{filepath}'")
    
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            # Read lines and strip the newline character from the end for cleaner diffing
            # difflib works better with lines without newlines, and it adds them back if needed.
            return [line.strip('\n') for line in f.readlines()]
    except Exception as e:
        raise IOError(f"Error reading file '{filepath}': {e}")

def _print_diff(diff_lines: list[str], file1_name: str, file2_name: str) -> None:
    """
    Prints the differences between two sequences of lines with colorized output.

    Args:
        diff_lines (list[str]): A list of diff output lines generated by difflib.
        file1_name (str): The name of the first file for context.
        file2_name (str): The name of the second file for context.
    """
    print(f"--- {file1_name}")
    print(f"+++ {file2_name}")
    
    for line in diff_lines:
        prefix = line[0] if line else ' '  # Get the first character (-, +, ?, or space)
        color = COLOR_MAP.get(prefix, COLOR_RESET) # Get the corresponding color
        print(f"{color}{line}{COLOR_RESET}") # Print the line with color and reset afterwards

def main():
    """
    Main function to parse arguments, perform the diff, and display results.
    """
    if len(sys.argv) != 3:
        print("Usage: python text_diff_tool.py <file1_path> <file2_path>")
        print("Compares two text files and displays their differences.")
        sys.exit(1)

    file1_path = sys.argv[1]
    file2_path = sys.argv[2]

    try:
        # Get content of both files
        lines1 = _get_file_content(file1_path)
        lines2 = _get_file_content(file2_path)

        # Create a Differ object
        differ = difflib.Differ()
        
        # Compare the two lists of lines
        # The compare method yields lines prefixed with ' ', '-', '+', or '?'
        diff_result = list(differ.compare(lines1, lines2))

        # Print the colorized differences
        _print_diff(diff_result, file1_path, file2_path)

    except FileNotFoundError as e:
        print(e)
        sys.exit(1)
    except IOError as e:
        print(e)
        sys.exit(1)
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()